### ISSUE TITLE
Create a mock server to test challenges

### ISSUE THREAD

**Issue by piraz** [candango/automatoes#10]
I don't think we can test challenges at runtime without exposing credentials and passwords.

Let's mock those servers so we can get the routine tested properly and we can execute on staging live after we get ACME V2 working without problems.

**Comment by cpu** [comment]
You might find [Pebble](https://github.com/letsencrypt/pebble) to be helpful for this. It also includes a [test server for responding to challenges](https://github.com/letsencrypt/pebble/tree/master/cmd/pebble-challtestsrv).

**Comment by piraz** [comment]
Thanks @cpu. I'll take a look at it.

**Comment by piraz** [comment]
Peeble running locally. Now we're cooking! @cpu

So the idea here is automate on peeble and test manually at stage?

**Comment by cpu** [comment]
> Peeble running locally. Now we're cooking! @cpu

Nice! :man_cook: 

> So the idea here is automate on peeble and test manually at stage?

:+1: I think that's a good approach. If you carefully implement the automated tests to accept a server URL you should be able to run them against staging by just changing the target server in a one-off manner before cutting a release. 

I generally don't recommend folks run automated tests against staging as part of every CI cycle because it can make builds somewhat unreliable when you depend on a networked service (e.g. we have planned maintenance periods and it shouldn't block dev work). Pebble works better for reliable CI tests :-)

**Comment by piraz** [comment]
@cpu you got it. Pebble on.
