### ISSUE TITLE
Add option to configure certificate file names

### ISSUE THREAD

**Issue by naglfar** [candango/automatoes#122]
Hi, 
would it be possible to add an option to the issue command to set the base name for the resulting certificate files? We've run into issues in the past where this would have been very helpful.

**Comment by piraz** [comment]
Let's do it.

**Comment by piraz** [comment]
I used the rebase and merge option, that is selected by some reason for me by default, and your commit was set as me by your name, instead of setting you as full author of the commit.

I'm really mad about it, next time I'll make sure I use the merge option that will keep you as author. Currently I'm trying to see how to change that option.

Thank you very much for the contribution.

The new release is 0.9.12.
